const menu = [
  {
    id: 1,
    name: "Headphones",
    category: "Headphones",
    price: "1,000",
    img: "https://www.energysistem.com/cdnassets/products/45305/principal_2000.jpg",
    title: "Premium Sound Bliss",
    desc: `Immerse yourself in the world of music with our premium headphones. Perfect for the audiophile in you, enjoy crystal-clear sound and deep bass for an unparalleled listening experience. Elevate your music journey with these stylish and comfortable headphones that redefine audio perfection.`,
  },
  {
    id: 2,
    name: "Smartphones",
    category: "Phones",
    price: "25,000",
    img: "https://img.uswitch.com/n36b8lzdmgnp/6flMYPMjJ0sZzNs16Fsqa/c525a3f838b0e62716631f003390506b/shutterstock_1736005427212121212.jpg?auto=format%2Ccompress&q=35&ixlib=react-9.5.1-beta.1",
    title: "Cutting-Edge Communication",
    desc: `Step into the future of communication with our latest smartphones. From sleek designs to powerful features, our phones are a blend of style and functionality. Whether you're a tech enthusiast or just looking for a reliable device, our smartphones ensure seamless connectivity and innovation at your fingertips.`,
  },
  {
    id: 3,
    name: "Laptops",
    category: "Laptops",
    price: "25,000",
    img: "https://i.rtings.com/assets/pages/IxCXzynA/apple-laptop-lineup-20220825-3-medium.jpg",
    title: "Portable Powerhouse",
    desc: `Experience the epitome of portability and performance with our laptops. Designed for on-the-go professionals and creative minds, these laptops deliver unmatched power in a sleek package. Stay productive and creative wherever you are, as our laptops redefine the meaning of portable computing.`,
  },
  {
    id: 4,
    name: "Woofers",
    category: "Entertainment",
    price: "3,500",
    img: "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/13/5444151/1.jpg?6209",
    title: "Bass Enchantment",
    desc: `Immerse yourself in the world of deep, rich bass with our premium woofers. Perfect for home entertainment systems or music enthusiasts, these woofers deliver a thunderous audio experience. Elevate your audio setup with our woofers and feel the music like never before.`,
  },
  {
    id: 5,
    name: "Smartwatches",
    category: "Wearables",
    price: "2,000",
    img: "https://ke.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/80/7871611/1.jpg?9553",
    title: "Smart Style, Smart Functionality",
    desc: `Stay connected and stylish with our smartwatches. Combining cutting-edge technology with sleek design, these smartwatches are more than just accessories—they're your personal assistant on your wrist. Experience the future of wearables with our feature-packed smartwatch collection.`,
  },
  {
    id: 6,
    name: "Routers",
    category: "Networking",
    price: "2,000",
    img: "https://shop.intellitech.co.ke/wp-content/uploads/2022/11/TL-WR940N_UN_6.0_01_no_award_normal_1533892413130o.jpg",
    title: "Seamless Connectivity",
    desc: `Power your digital life with our high-performance routers. Whether you're streaming, gaming, or working, our routers provide a seamless and reliable connection. Say goodbye to buffering and lag with our advanced router technology that keeps you connected at all times.`,
  },
  {
    id: 7,
    name: "Televisions",
    category: "Entertainment",
    price: "20,000",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqHALgncNG2nt_BzsEiZXEFg9Q01F56AJYRQ&usqp=CAU",
    title: "Immersive Viewing Experience",
    desc: `Transform your living space with our cutting-edge televisions. Experience stunning visuals and lifelike colors that bring your favorite movies and shows to life. With sleek designs and advanced display technology, our televisions redefine home entertainment.`,
  },
  {
    id: 8,
    name: "Flash Drives",
    category: "Drives",
    price: "1,00",
    img: "https://technohubdigitalsolutions.co.ke/wp-content/uploads/2023/06/SDDDC4-128G-G46-2.png",
    title: "Data on the Go",
    desc: `Carry your data in style with our high-speed flash drives. Whether you're a student, professional, or tech enthusiast, our flash drives offer reliable and speedy data transfer. Store, transfer, and access your files with ease using our compact and stylish flash drives.`,
  },
  {
    id: 9,
    name: "Wireless Earbuds",
    category: "Audio",
    price: "1,500",
    img: "https://i5.walmartimages.com/seo/VEATOOL-Bluetooth-Headphones-True-Wireless-Earbuds-60H-Playback-LED-Power-Display-Earphones-Charging-Case-IPX7-Waterproof-in-Ear-Mic-TV-Smart-Phone-C_67f761e1-eefc-47d8-8dd0-5ad824debf9a.01f64ab355f971030adaca50c4b959b3.jpeg",
    title: "Wireless Freedom",
    desc: `Cut the cords and experience true wireless freedom with our Bluetooth earphones. Perfect for on-the-go lifestyles, these earphones offer crystal-clear audio and a comfortable fit. Embrace the future of audio technology with our Bluetooth earphones that keep you connected without compromise.`,
  },
]

export default menu
